# Generated by Django 4.2.3 on 2023-07-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date_relase',
            new_name='release_date',
        ),
    ]
