# Generated by Django 4.2.3 on 2023-07-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_date_relase_book_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_added',
            new_name='user',
        ),
    ]
